### PR TITLE
feat: add volume to response

### LINKED ISSUE #63: Add 2 more parameters about the volumes
item[5] and item[6] _probably_ (help wanted) represents the volume, add them into the APIs.

Eg for dow jones:
```
        [
            1645660800000,
            32830.33,
            33269.34,
            32272.64,
            33223.83,
            593186432, // volume?
            0 // volume?
        ],
```

### PR DESCRIPTION
**Pull request by liardoecp**
Added volume and removed value because it's not necessary (use price_close)
Fixes #63

### CODE REVIEW

**Comment by DavideViolante** [comment]
Not returning "value" is a breaking change, so I would keep `value: item[1]`

**Comment by liardoecp** [comment]
What does the value indicate? Should it be the opening price (like now) or the closing price (maybe more correct)?

**Comment by DavideViolante** [comment]
If the closing price is more "correct" I would add it.
I had same doubt years ago here https://github.com/DavideViolante/investing-com-api/issues/62

**Comment by liardoecp** [comment]
fixed it

**Pull request merged**
